### ISSUE TITLE
Tinge - Conflicting Option Strings

### ISSUE THREAD

**Issue by keeb-zz** [alunduil/margarine#14]
``` ======================================================================
ERROR: Failure: ArgumentError (argument --flask-host: conflicting option string(s): --flask-host)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keeb/websites/margarine/virtualenv/local/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/keeb/websites/margarine/virtualenv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/keeb/websites/margarine/virtualenv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/keeb/websites/margarine/margarine/tinge/__init__.py", line 65, in <module>
    "help": "Enable debugging of the flask application.",
  File "/home/keeb/websites/margarine/margarine/parameters.py", line 163, in __init__
    self._add_argument_parameters(name, parameters)
  File "/home/keeb/websites/margarine/margarine/parameters.py", line 327, in _add_argument_parameters
    parser.add_argument(*options["args"], **options["kwargs"])
  File "/usr/lib/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --flask-host: conflicting option string(s): --flask-host
-------------------- >> begin captured logging << --------------------
```

Removing the Parameters sections solve the problem, but probably not the best way to accomplish the desired goal.

**Comment by alunduil** [comment]
Yep, I knew duplicating that would come back to haunt me at some point.  I think the right move is to move the flask parameters to their own module but I'd like to do it without any conflicting namespaces.  Any suggestions on a good module name for flask parameters?  Perhaps maragarine.parameters.web?

**Comment by keeb-zz** [comment]
Would you then consider moving the code that's inside `parameters.py` in to `parameters/__init__.py` and have `web.py` be a module?

**Comment by alunduil** [comment]
That was what I was thinking and I think it remains the most clear by factoring it in such a way.  What do you think?

**Comment by keeb-zz** [comment]
How about environment variables?

**Comment by alunduil** [comment]
The Parameters object actually multiplexes the environment variables, configuration file variables and command line parameters into one consistent view.

How were you thinking of using environment variables to declare these options?  Was is something like the following?

TINGE_FLASK_PORT=5000 bin/tinge

If so, that's already handled by that parameters declaration.  

I'm thinking your idea of making parameters a package rather than just a module is the best option.  Let me know what you think.

**Comment by keeb-zz** [comment]
I was not aware of that but I am really happy about it :) I'll submit a pull request on this next.

**Comment by alunduil** [comment]
Currently working on finishing the move of parameters from particular modules to a common module.  Will need to verify everything is hooked up again next.  In the process, I have been fixing relevant lint problems and generally trying to improve the code base.

**Comment by alunduil** [comment]
Looks like the branch for this bug is ready for review.  I feel like I've missed something basic so a double check on all of the Parameters items would be excellent.  Also, part of this solution should be a review of all the naming of parameters for margarine.

**Comment by dubsquared** [comment]
With the move to crumbs, is still still relevant?

**Comment by alunduil** [comment]
Yes, crumbs only abstracts the data structures not the declaration of the parameters (those are still domain specific).  This means the parameters for flask will still need to be in a single location.  We may iterate on what's in this issue's branch but it's a good place to start resolving the conflict.

**Comment by alunduil** [comment]
Closing this issue as the parameters have been split into their own module and imported in relevant locations.
