### ISSUE TITLE
Review Tinge Article Presentation

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#22]
The frontend for articles has been templated and stubbed out but needs a check for UX and presentation.  

If any elements need to be added to the frontend an appropriate trello item should be added to the back burner.  If anything is incorrect about what is currently there another issue should be created and linked from this issue.

**Comment by dubsquared** [comment]
How are you intending to present the article?  Static web with javascript for dynamic elements?

**Comment by alunduil** [comment]
That's how it currently is.  If you check out margarine/tinge/templates, you'll see the collection of jinja files that create the presentation of the home page and the article presentation.  If you want to see it live, we'll have to wait until the development environment fully works.

**Comment by jruels** [comment]
I'm not sure what to review on this.  I think using javascript sounds good :)

**Comment by alunduil** [comment]
This issue is more for layout review (does it look and function the way people want) as well as a review of the documentation layout.  Is the HTML properly structured?  The question of using javascript or not wasn't originally part of this but we can certainly discuss those issues here as well.

This issue is meant to be a review of the user interface (frontend|tinge) for margarine's articles.  Do we drop SEO and searchability for statically hostable content, &c?

**Comment by hhoover** [comment]
The HTML looks good, but I think we should use Bootstrap 3, recently released. I'll open a different issue for that.
