### ISSUE TITLE
Review Blend Article Submissions

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#24]
The test for blend's article creation mechanism need to be reviewed for correctness as well as any possibility of improvement.

Currently, the tests live in the tests/refactor branch and issue 21 is open to track the movement of this branch in master.

**Comment by hhoover** [comment]
Since issue 21 is closed can this be closed as well?

**Comment by alunduil** [comment]
I suppose but it would be nice to have someone check it for defects nonetheless.  I'll close this issue and ensure a card is still available in 'to review' on trello.
