### ISSUE TITLE
Review Blend Article Retrieval

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#25]
The article read tests for blend need to be reviewed and verified.  Verified that the tests actually cover good cases as well as cover the functionality we want handled by the article retrieval system.

Also, do we want to have two presentations of articles?  One with the body and one without?

**Comment by hhoover** [comment]
which files

**Comment by alunduil** [comment]
The tests are in `test_margarine/test_unit/test_blend/test_article.py`.

The testing directory layout is the following:

:test_margarine: All tests for margarine
:test_unit: All unit tests for margarine
:test_blend: All test type for blend
:test_article.py: All test type for component with subcomponent article

**Comment by alunduil** [comment]
Invalidated.
