### ISSUE TITLE
Review Automated Integration Test Generation

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#27]
The automated generation of the integration tests should be working correctly.  The list of created tests needs to be verified for accuracy and the tests checked for any lack of coverage.

**Comment by dubsquared** [comment]
Took a look at all the test files created; lacking documentation of what the test is actually solving for.  Once that is added it'll be easier to determine if full coverage is met.

**Comment by alunduil** [comment]
I apologize, I meant integration completeness rather than code coverage.  Does that change the picture or am I just misunderstanding what's missing?

**Comment by dubsquared** [comment]
Ah, that changes what I'm looking at.  Will get back to you.

**Comment by alunduil** [comment]
Don't work on this too much right now.  I've started noodling a new way to craft the tests that I'll implement as we verify the stories that are currently implemented.  I'm going to close this one as invalid in the meantime.
