### ISSUE TITLE
Testing of Margarine

### ISSUE THREAD

**Issue by dubsquared** [alunduil/margarine#45]
There is a lot of testing that is going on, but not a lot of information about how and why.  Can we get some clarification on 'all things testing' so everyone can contribute?

**Comment by alunduil** [comment]
Sure, let's either setup a meeting to discuss what needs to be documented and how or start pointing out issues with a lack of clarity in the testing here.  Let me know how you want to proceed and everyone can feel free to use this issue to let us know where the tests are unclear.

**Comment by dubsquared** [comment]
Sounds good, I'll point the team here so we can start to dissect the testing questions and we'll try to get a meeting setup sooner rather than later.

**Comment by hhoover** [comment]
We had the meeting, and Alex is documenting his tests.
