### ISSUE TITLE
Mongo Connection Doesn't SSL

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#53]
The Mongo connection items need to be able to use SSL but how to implement this is still undecided.

See http://docs.mongodb.org/manual/tutorial/configure-ssl/, to learn about using SSL with pymongo but how do we want to incorporate it into our URLs is the question.

**Comment by alunduil** [comment]
The choices we have for this are the following:
- Change the protocol to be something like `mongodbs://`
- Change the protocol to be composite like `mongodb+ssl://`
- Append the query parameter after the database like `/prod?ssl=true`

The last has the advantage that for mongo at least it can be passed straight through without modification but we would still need to verify the URI helper can handle query strings properly.

The first two seem needlessly complex but I wanted to ask everyone if they could think of reasons that they might be preferred before just implementing the third option.

**Comment by dubsquared** [comment]
It seems like ssl=true is preferred, after a quick scan of the interwebs that methods seems to be the overwhelming favorite.  Why would the URI helper have issues with it?

**Comment by alunduil** [comment]
Currently, the URI helper doesn't parse query strings so that would be code to add to that component as well as the mongo connection retriever.  That's all I meant by the comment.  It's a small enough fix and won't be an issue just being open about what is required.

**Comment by alunduil** [comment]
Looks like adding `?ssl=true` to the datastore URL will add SSL without any code changes required.  Closing this issue as resolved until something similar pops up.
