### ISSUE TITLE
Pass Username and Password to Redis

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#7]
The current get_keystore function does not pass the username and password through to Redis from the URL.

**Comment by alunduil** [comment]
Looks like Redis ignores usernames and thus, the commit will need to be updated to do the same.

**Comment by dubsquared** [comment]
lgtm, where do we need to test the connection string before merge?

**Comment by alunduil** [comment]
Good question.  I suppose we could put a particular connection string in a functional test but that doesn't sound super secure.  Perhaps, just set the environment variable and run the method?  I hate hand driven tests but I can't think of a good test.

Unless, we want to setup a Redis server with a password to test against in vagrant?  Would that work out well enough?

**Comment by dubsquared** [comment]
Lets do that, we're having some issues with RedisToGo so we might need to roll our own redis until we can get the redis service kinks worked out.

**Comment by alunduil** [comment]
Sounds like a plan.  I'll spin up a redis server as part of the staging environment and we can revisit the question of spinning up a redis box locally for testing at another time.

**Comment by alunduil** [comment]
Merged into master and should be working correctly.
