### ISSUE TITLE
Testing Cloud Files Locally

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#84]
Research needs to be done on whether swift can serve items via a CDN URL like Rackspace Cloud Files.  If so, we should look at developing a vagrant box to test this storage medium in limited system tests.  If not, we need to find another way to develop around this mechanism.

**Comment by gtmanfred** [comment]
:+1:

**Comment by alunduil** [comment]
After reviewing the advanced features we want to implement, this isn't something we should be looking to do.  While it would simplify the application a lot and be very interesting, it doesn't allow indexed searches of the articles without something like elasticsearch anyway.  Might as well store the information in MongoDB like we have been and figure out alternatives later.
