### ISSUE TITLE
Add Top Level Exception Catcher

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#9]
Catch all the exceptions so they get logged.

**Comment by alunduil** [comment]
Added a branch, issues/9, with top-level exception handlers for tinge, blend, and spread.  These need to be tested before merging as well as reviewed.

**Comment by jruels** [comment]
I'm happy to try and look at this, but I have no idea what code to even review or how to test for exception handling. Please point me in the right direction and I'll start reviewing.

**Comment by alunduil** [comment]
I've created a branch with the potential fixes for this.  The diff should be small enough to look through.  Sorry I forgot to attach this issue to the commit.

Testing for exception handling doesn't truly happen at this level.  This is meant to capture all uncaught exceptions in the log file so that if an error does occur during execution we have a place to begin debugging or looking further.

I also wonder if the main mechanisms need to be reworked as part of this but was holding off on that thought process unless you want to ponder on it with me.

If you need anything else, let me know.

**Comment by jruels** [comment]
Reviewed with Alex.  Looks good to me.

**Comment by alunduil** [comment]
Merged into master and branch removed.
